[project]
name = "bootcamp"
version = "0.1.0"
description = ""
authors = [
    {name = "mksouzza",email = "mksouzza@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11.5"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
